Repository puppetlabs/r10k, pull requests merged in 2021-11, with the labels that each got.

#1242 Implement R10K::Util::Cacheable
  lib/r10k/forge/module_release.rb
  lib/r10k/git/cache.rb
  lib/r10k/util/cacheable.rb
  spec/unit/git/cache_spec.rb
  spec/unit/util/cacheable_spec.rb
Labels: refactor

#1244 Tarball
  doc/dynamic-environments/configuration.mkd
  doc/puppetfile.mkd
  lib/r10k/environment.rb
  lib/r10k/environment/tarball.rb
  lib/r10k/initializers.rb
  lib/r10k/module.rb
  lib/r10k/module/tarball.rb
  lib/r10k/tarball.rb
  r10k.gemspec
  spec/fixtures/tarball/tarball.tar.gz
  spec/shared-contexts/tarball.rb
  spec/spec_helper.rb
  spec/unit/environment/tarball_spec.rb
  spec/unit/module/tarball_spec.rb
  spec/unit/tarball_spec.rb
Labels: feature, awaiting codeowner action

#1240 use correct reference when using strip_component
  CHANGELOG.mkd
  lib/r10k/environment/name.rb
  lib/r10k/source/git.rb
  spec/unit/action/deploy/module_spec.rb
  spec/unit/environment/name_spec.rb
Labels: bug, awaiting user feedback
