Repository puppetlabs/r10k, pull requests merged in 2021-09, with the labels that each got.

#1214 (RK-308) Allow respecting `forge` declaration in puppetfile
  CHANGELOG.mkd
  doc/dynamic-environments/configuration.mkd
  doc/puppetfile.mkd
  lib/r10k/action/deploy/environment.rb
  lib/r10k/action/deploy/module.rb
  lib/r10k/module_loader/puppetfile.rb
  lib/r10k/puppetfile.rb
  lib/r10k/settings.rb
  spec/fixtures/unit/puppetfile/forge-override/Puppetfile
  spec/unit/module_loader/puppetfile_spec.rb
  spec/unit/settings_spec.rb
Labels: feature, has jira ticket

#1218 Bump the version of puppet_forge
  r10k.gemspec
Labels: do not merge, has jira ticket, awaiting user feedback, dependency bump

#1216 [#1215] Ensure module postrun command only runs for modified envs
  CHANGELOG.mkd
  lib/r10k/action/deploy/environment.rb
  lib/r10k/action/deploy/module.rb
  lib/r10k/content_synchronizer.rb
  lib/r10k/environment/base.rb
  lib/r10k/git/stateful_repository.rb
  lib/r10k/module/base.rb
  lib/r10k/module/definition.rb
  lib/r10k/module/forge.rb
  lib/r10k/module/git.rb
  lib/r10k/module/local.rb
  lib/r10k/module/svn.rb
  spec/unit/action/deploy/module_spec.rb
  spec/unit/module/forge_spec.rb
  spec/unit/module/git_spec.rb
  spec/unit/module/svn_spec.rb
  spec/unit/puppetfile_spec.rb
Labels: bug
